spring:
  application:
    name: kappa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/draft?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  #   与Jedis相比，lettuce 则完全克服了其线程不安全的缺点.
  #   lettuce 是一个可伸缩的线程安全的Redis客户端，支持同步、异步和响应式模式。
  #   多个线程可以共享一个连接实例， 而不必担心多线程并发问题。
  #   它基于优秀Netty NIO框架构建，支持Redis的更多高级功能。
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

server:
  error:
    include-message: always
