spring:
  application:
    name: kappa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/draft?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  #   与Jedis相比，lettuce 则完全克服了其线程不安全的缺点.
  #   lettuce 是一个可伸缩的线程安全的Redis客户端，支持同步、异步和响应式模式。
  #   多个线程可以共享一个连接实例， 而不必担心多线程并发问题。
  #   它基于优秀Netty NIO框架构建，支持Redis的更多高级功能。
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

server:
  error:
    include-message: always

rsa:
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArVZ9J3YMLbMV3Yl5rexHj4BQg2j1iZkDqcXsWJWOAvoA3uPfgd/WCQgqyTKW1DDQpiyEKZiYGpuzHFxqzTyyGhgAlkk44+Q4hHOM08XTI2WB1KdvJFd1+r0mwl3e1AkJsb6CniK6YJ2ETdoyR7ybnkLgWI/U3q5ZOzRxqu6t3gunF2DENpb5giyD60EjAl4ppzS1qhuUYoiDJjZDdQi5lcpFnw8r36vVdHRTbKeudW088tE2Y6BSwVUp1zwYVdzjP9p3AnvmVTrV3wkbD9yXSiWpBcRNy/0JTTgJ2DYZ38WRpA+ZAl6q0uVFthQwKgjse58QMunKd/IhfcRFbBgVCQIDAQAB
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCtVn0ndgwtsxXdiXmt7EePgFCDaPWJmQOpxexYlY4C+gDe49+B39YJCCrJMpbUMNCmLIQpmJgam7McXGrNPLIaGACWSTjj5DiEc4zTxdMjZYHUp28kV3X6vSbCXd7UCQmxvoKeIrpgnYRN2jJHvJueQuBYj9Terlk7NHGq7q3eC6cXYMQ2lvmCLIPrQSMCXimnNLWqG5RiiIMmNkN1CLmVykWfDyvfq9V0dFNsp651bTzy0TZjoFLBVSnXPBhV3OM/2ncCe+ZVOtXfCRsP3JdKJakFxE3L/QlNOAnYNhnfxZGkD5kCXqrS5UW2FDAqCOx7nxAy6cp38iF9xEVsGBUJAgMBAAECggEAGYbwtISGg55pnHAYCtyOp1wCv2+QJXzy1KhQx7Tyro6J3Ulay6Iev8LDplC8dLBhse9BYWzXDagbZxRXKDWFlyEsyPUsmycriZoIxdFO6FoVFi+4RvZYah48HIi9faV9F3+Sdd5wazUXXG3DVNw6YMLBjllURJ0RiA4PpVg0I8x+dwtLW3sRgODtT1sCdALwOJVAtdZm4meh16y3kO0uLtkLgVFRB5Efb0j+CfQRLYZKZJhO76r9oXJ7Rr2NgfxcbTYtToseNSagj6z2tnfHdOQhEx+xOvvpIMU533iFqdkEbIEAF2MynB02fa97V835JBHi4g+kZKJ8+RntB7qKLwKBgQDOuuT03GOheYxcqp3mjpaoXUzxC6Ih8i6kczfKPTUhdzQLqrw5oIX9KJiOGSfYOn/REc9IcspNl7w2mMpboKu1hZq+eL890bT/Nq8PcDkvfGdNE1km3f91BVZdmL5f0DdzjbRU7Gv7NCQTYGV22j/DMfU8YzxHEEurEBsEslQeqwKBgQDWpkEZ01N6hEweffC0pZu1Bh9869fQmwPbqtKs5aJcsNzZ92EI5s3qo+9B889TsCO0qjPtVNJTSqueDhTlLtYcCKpcknqNiAXn4/OLf9lbqg2CQTO/G8tdmJKSx4AvPFLQqYCi4wbbnaU16w4lAZwtaUDRkkKKrbDlp+yzabaLGwKBgD3mGf3zK2XDBjMM5yCMmzGoVgxqpk4xvKOC2DaW4xy1G4FOyvMaTGRDzoHlqFeHFJReF8mijU50W2ehkh2jWyaL7YyQjPqOmvo7vmkJ+iVsw2WBoJURrZa1VWnK/V2k86WGzXMMIzzhHNgsadUPfj4M7Ff7gqXojC+ZL+3VE3jnAoGASPFgiCUvZiAVOft0U/8/RaoaAzqmMWasTfbj9wtmPHeB5bRSTlMYwNcK1G/FEdx2lcuNL+a2PsXOQjzozuU2r3omYqUIbpY944qsVciRlbvZMV1090m7t0fE74pKPkMSpYQkibX6u6D75rHFMcA1UZ1GALHiWPwjdDe3kVSoSucCgYAqb4G+egQyt816uDK890Q2rHd8HGul0XHmV+TFAgyfqanKclzMVNz0/w3u2EG1D7H8TOVerjEoETHjuk9H0LlLEiffpnrRbTUgV1NPFgaWWMZuw6Z9SERFySksibqvZOqxDjv7t9lULfNwMNMTN7JYJzbjnFa8OwK5FLjxBypUdw==
